@echo off
setlocal EnableDelayedExpansion
REM ──────────────────────────────────────────────────────────────
REM Asimov's Mind — Setup Script (Windows)
REM One command to install the full Agent Friday ecosystem.
REM ──────────────────────────────────────────────────────────────

title Asimov's Mind Setup
color 0B

echo.
echo   ============================================================
echo            ASIMOV'S MIND - SETUP
echo            Agent Friday Ecosystem Installer
echo   ============================================================
echo.

set "REPO_DIR=%~dp0"
set "FRIDAY_DATA=%USERPROFILE%\.friday"
set "DESKTOP_DIR=%REPO_DIR%interfaces\desktop"

REM ── [1/8] Check prerequisites ─────────────────────────────────
echo [1/8] Checking prerequisites...

python --version >nul 2>&1
if errorlevel 1 (
    echo ERROR: Python not found. Install Python 3.10+ from https://python.org
    pause
    exit /b 1
)
python -c "import sys; print(f'  Python {sys.version_info.major}.{sys.version_info.minor} found')"

node --version >nul 2>&1
if errorlevel 1 (
    echo   WARNING: Node.js not found. The Claude Code plugin requires Node 18+.
    echo   Install from: https://nodejs.org/
) else (
    for /f %%v in ('node --version') do echo   Node.js %%v found
)

REM ── [2/8] Create ~/.friday data dirs ──────────────────────────
echo [2/8] Creating data directory at %FRIDAY_DATA%...

for %%D in (vault integrity audio-cache vibe-code-logs finance health career-ops career-ops\data career-ops\reports flow-queue outreach content futurespeak wiki) do (
    if not exist "%FRIDAY_DATA%\%%D" mkdir "%FRIDAY_DATA%\%%D" 2>nul
)

if not exist "%FRIDAY_DATA%\profile.json" (
    if exist "%DESKTOP_DIR%\profile.example.json" (
        copy "%DESKTOP_DIR%\profile.example.json" "%FRIDAY_DATA%\profile.json" >nul
        echo   Seeded %FRIDAY_DATA%\profile.json (edit to personalize Friday^)
    )
)
echo   Created %FRIDAY_DATA%\

REM ── [3/8] Python venv ─────────────────────────────────────────
echo [3/8] Creating Python virtual environment...

if not exist "%REPO_DIR%venv" (
    python -m venv "%REPO_DIR%venv"
    echo   Created venv\
) else (
    echo   venv\ already exists, skipping
)

call "%REPO_DIR%venv\Scripts\activate.bat"

REM ── [4/8] Install Python deps ─────────────────────────────────
echo [4/8] Installing Python dependencies...

if exist "%DESKTOP_DIR%\requirements.txt" (
    pip install -q --upgrade pip
    pip install -q -r "%DESKTOP_DIR%\requirements.txt"
    echo   Installed desktop requirements
)
if exist "%REPO_DIR%requirements.txt" (
    pip install -q -r "%REPO_DIR%requirements.txt"
)

REM ── [5/8] Install Node deps ───────────────────────────────────
echo [5/8] Installing Node.js dependencies...

node --version >nul 2>&1
if not errorlevel 1 (
    if exist "%REPO_DIR%mcp\friday-core\package.json" (
        pushd "%REPO_DIR%mcp\friday-core"
        npm install --silent 2>nul
        popd
    )
    echo   Node packages installed
) else (
    echo   Skipped (Node.js not installed^)
)

REM ── [6/8] Prompt for API keys ─────────────────────────────────
echo [6/8] API keys...
echo.
echo   Anthropic API key (REQUIRED) - All reasoning and chat uses Claude.
echo   Get one at: https://console.anthropic.com
:askanthropic
set "ANTHROPIC_API_KEY="
set /p "ANTHROPIC_API_KEY=  ANTHROPIC_API_KEY: "
if "%ANTHROPIC_API_KEY%"=="" (
    echo   Required.
    goto askanthropic
)

echo.
echo   Gemini API key (REQUIRED) - Voice mode and image creation use Gemini.
echo   Get one at: https://aistudio.google.com/app/apikey
:askgemini
set "GEMINI_API_KEY="
set /p "GEMINI_API_KEY=  GEMINI_API_KEY: "
if "%GEMINI_API_KEY%"=="" (
    echo   Required.
    goto askgemini
)

REM ── [7/8] Write gitignored start.bat ──────────────────────────
echo [7/8] Writing start.bat (gitignored^)...

> "%REPO_DIR%start.bat" echo @echo off
>> "%REPO_DIR%start.bat" echo REM Friday Desktop launcher - generated by setup.bat
>> "%REPO_DIR%start.bat" echo REM DO NOT COMMIT - contains API keys
>> "%REPO_DIR%start.bat" echo set "ANTHROPIC_API_KEY=%ANTHROPIC_API_KEY%"
>> "%REPO_DIR%start.bat" echo set "GEMINI_API_KEY=%GEMINI_API_KEY%"
>> "%REPO_DIR%start.bat" echo call "%%~dp0venv\Scripts\activate.bat"
>> "%REPO_DIR%start.bat" echo cd /d "%%~dp0interfaces\desktop"
>> "%REPO_DIR%start.bat" echo python server.py
echo   Wrote start.bat

REM ── [8/8] Build Desktop UI ────────────────────────────────────
echo [8/8] Building Desktop UI...

if exist "%DESKTOP_DIR%\build_ui.py" (
    pushd "%DESKTOP_DIR%"
    python build_ui.py
    popd
    echo   Desktop UI assembled
)

REM ── Done ──────────────────────────────────────────────────────
echo.
echo   ============================================================
echo            SETUP COMPLETE
echo   ============================================================
echo.
echo   Next steps:
echo.
echo   1. (Optional^) Personalize Friday by editing your profile:
echo      notepad %FRIDAY_DATA%\profile.json
echo      Template: %DESKTOP_DIR%\profile.example.json
echo.
echo   2. Start Friday Desktop:
echo      start.bat
echo      Open http://localhost:5000
echo.
echo   3. (Optional^) Install Claude Code for development:
echo      https://claude.com/claude-code
echo      Then: claude plugin add .
echo.
echo   Data: %FRIDAY_DATA%
echo   Docs: README.md, docs\, GETTING_STARTED.md
echo.

pause
endlocal
