#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────
# Asimov's Mind — Setup Script (macOS / Linux)
# One command to install the full Agent Friday ecosystem.
# ──────────────────────────────────────────────────────────────────
set -e

CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

REPO_DIR="$(cd "$(dirname "$0")" && pwd)"
FRIDAY_DATA="${FRIDAY_DATA_DIR:-$HOME/.friday}"
DESKTOP_DIR="$REPO_DIR/interfaces/desktop"

echo ""
echo -e "${CYAN}  ╔══════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}  ║         ASIMOV'S MIND — SETUP                   ║${NC}"
echo -e "${CYAN}  ║         Agent Friday Ecosystem Installer         ║${NC}"
echo -e "${CYAN}  ╚══════════════════════════════════════════════════╝${NC}"
echo ""

# ── [1/8] Check prerequisites ────────────────────────────────────
echo -e "${YELLOW}[1/8] Checking prerequisites...${NC}"

if ! command -v python3 &> /dev/null; then
    echo -e "${RED}ERROR: Python 3 not found. Install Python 3.10+ first.${NC}"
    exit 1
fi
echo "  Python $(python3 -c 'import sys;print(f"{sys.version_info.major}.{sys.version_info.minor}")') found"

if ! command -v node &> /dev/null; then
    echo -e "${YELLOW}  WARNING: Node.js not found. The Claude Code plugin requires Node 18+.${NC}"
else
    echo "  Node.js $(node --version) found"
fi

# ── [2/8] Create ~/.friday data directory ────────────────────────
echo -e "${YELLOW}[2/8] Creating data directory at $FRIDAY_DATA...${NC}"

mkdir -p "$FRIDAY_DATA/vault"
mkdir -p "$FRIDAY_DATA/integrity"
mkdir -p "$FRIDAY_DATA/audio-cache"
mkdir -p "$FRIDAY_DATA/vibe-code-logs"
mkdir -p "$FRIDAY_DATA/finance"
mkdir -p "$FRIDAY_DATA/health"
mkdir -p "$FRIDAY_DATA/career-ops/data"
mkdir -p "$FRIDAY_DATA/career-ops/reports"
mkdir -p "$FRIDAY_DATA/flow-queue"
mkdir -p "$FRIDAY_DATA/outreach"
mkdir -p "$FRIDAY_DATA/content"
mkdir -p "$FRIDAY_DATA/futurespeak"
mkdir -p "$FRIDAY_DATA/wiki"

# Seed profile.json from template if missing
if [ ! -f "$FRIDAY_DATA/profile.json" ] && [ -f "$DESKTOP_DIR/profile.example.json" ]; then
    cp "$DESKTOP_DIR/profile.example.json" "$FRIDAY_DATA/profile.json"
    echo "  Seeded $FRIDAY_DATA/profile.json (edit to personalize Friday)"
fi
echo "  Created $FRIDAY_DATA/"

# ── [3/8] Python venv ────────────────────────────────────────────
echo -e "${YELLOW}[3/8] Creating Python virtual environment...${NC}"

if [ ! -d "$REPO_DIR/venv" ]; then
    python3 -m venv "$REPO_DIR/venv"
    echo "  Created venv/"
else
    echo "  venv/ already exists, skipping"
fi

# shellcheck disable=SC1091
source "$REPO_DIR/venv/bin/activate"

# ── [4/8] Install Python dependencies ────────────────────────────
echo -e "${YELLOW}[4/8] Installing Python dependencies...${NC}"
if [ -f "$DESKTOP_DIR/requirements.txt" ]; then
    pip install -q --upgrade pip
    pip install -q -r "$DESKTOP_DIR/requirements.txt"
    echo "  Installed desktop requirements"
fi
if [ -f "$REPO_DIR/requirements.txt" ]; then
    pip install -q -r "$REPO_DIR/requirements.txt"
fi

# ── [5/8] Install Node deps ──────────────────────────────────────
echo -e "${YELLOW}[5/8] Installing Node.js dependencies...${NC}"
if command -v node &> /dev/null && [ -f "$REPO_DIR/mcp/friday-core/package.json" ]; then
    (cd "$REPO_DIR/mcp/friday-core" && npm install --silent 2>/dev/null) || echo "  npm install skipped (will auto-install on first run)"
    echo "  Node packages installed"
else
    echo "  Skipped (Node.js not installed or package.json missing)"
fi

# ── [6/8] Prompt for API keys ────────────────────────────────────
echo -e "${YELLOW}[6/8] API keys...${NC}"
echo ""
echo -e "  ${CYAN}Anthropic API key${NC} (REQUIRED) — All reasoning and chat uses Claude."
echo "  Get one at: https://console.anthropic.com"
read -r -p "  ANTHROPIC_API_KEY: " ANTHROPIC_API_KEY
while [ -z "$ANTHROPIC_API_KEY" ]; do
    echo -e "  ${RED}Required.${NC}"
    read -r -p "  ANTHROPIC_API_KEY: " ANTHROPIC_API_KEY
done

echo ""
echo -e "  ${CYAN}Gemini API key${NC} (REQUIRED) — Voice mode and image creation use Gemini."
echo "  Get one at: https://aistudio.google.com/app/apikey"
read -r -p "  GEMINI_API_KEY: " GEMINI_API_KEY
while [ -z "$GEMINI_API_KEY" ]; do
    echo -e "  ${RED}Required.${NC}"
    read -r -p "  GEMINI_API_KEY: " GEMINI_API_KEY
done

# ── [7/8] Generate gitignored start.sh ───────────────────────────
echo -e "${YELLOW}[7/8] Writing start.sh (gitignored)...${NC}"
cat > "$REPO_DIR/start.sh" <<EOF
#!/usr/bin/env bash
# Friday Desktop launcher — generated by setup.sh
# DO NOT COMMIT — contains API keys
export ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY"
export GEMINI_API_KEY="$GEMINI_API_KEY"

REPO_DIR="\$(cd "\$(dirname "\$0")" && pwd)"
source "\$REPO_DIR/venv/bin/activate"
cd "\$REPO_DIR/interfaces/desktop"
exec python server.py
EOF
chmod +x "$REPO_DIR/start.sh"
echo "  Wrote start.sh"

# ── [8/8] Build Desktop UI ───────────────────────────────────────
echo -e "${YELLOW}[8/8] Building Desktop UI...${NC}"
if [ -f "$DESKTOP_DIR/build_ui.py" ]; then
    (cd "$DESKTOP_DIR" && python3 build_ui.py)
    echo "  Desktop UI assembled"
fi

# ── Done ─────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}  ╔══════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}  ║         SETUP COMPLETE                           ║${NC}"
echo -e "${GREEN}  ╚══════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${CYAN}Next steps:${NC}"
echo ""
echo "  1. (Optional) Personalize Friday by editing your profile:"
echo "     \$EDITOR $FRIDAY_DATA/profile.json"
echo "     Template: $DESKTOP_DIR/profile.example.json"
echo ""
echo "  2. Start Friday Desktop:"
echo "     ./start.sh"
echo "     Open http://localhost:5000"
echo ""
echo "  3. (Optional) Install Claude Code for development:"
echo "     https://claude.com/claude-code"
echo "     Then: claude plugin add ."
echo ""
echo -e "  ${YELLOW}Data: $FRIDAY_DATA${NC}"
echo -e "  ${YELLOW}Docs: README.md, docs/, GETTING_STARTED.md${NC}"
echo ""
