#Requires -Version 5.1
<#
.SYNOPSIS
  Agent Friday — One-Line Installer for Windows
  FutureSpeak.AI · Asimov's Mind

.DESCRIPTION
  Installs Agent Friday on Windows via PowerShell.

  One-liner:
    iex (irm https://raw.githubusercontent.com/FutureSpeakAI/asimovs-mind/main/scripts/install.ps1)

  What this does:
    1. Checks Python 3.10+ (offers download link if missing)
    2. Clones the repo to %USERPROFILE%\.friday-desktop
    3. Creates a Python virtual environment
    4. Installs all dependencies
    5. Registers the `friday` command in the user PATH
    6. Runs `friday setup` to configure your agent
#>

Set-StrictMode -Off
$ErrorActionPreference = "Stop"

# ── Banner ───────────────────────────────────────────────────────
function Write-Banner {
    $cyan    = "`e[36m"
    $magenta = "`e[35m"
    $green   = "`e[32m"
    $dim     = "`e[2m"
    $bold    = "`e[1m"
    $reset   = "`e[0m"

    Write-Host ""
    Write-Host "${cyan}${bold}" -NoNewline
    Write-Host "     ██████╗ ██╗██████╗  █████╗ ██╗   ██╗"
    Write-Host "    ██╔════╝ ██║██╔══██╗██╔══██╗╚██╗ ██╔╝"
    Write-Host "    ██║  ███╗██║██║  ██║███████║ ╚████╔╝ "
    Write-Host "    ██║   ██║██║██║  ██║██╔══██║  ╚██╔╝  "
    Write-Host "    ╚██████╔╝██║██████╔╝██║  ██║   ██║   "
    Write-Host "     ╚═════╝ ╚═╝╚═════╝ ╚═╝  ╚═╝   ╚═╝  "
    Write-Host "${reset}" -NoNewline
    Write-Host ""
    Write-Host "  ${magenta}${bold}A S I M O V ' S   M I N D${reset}  ${dim}by FutureSpeak.AI${reset}"
    Write-Host ""
    Write-Host "  ${dim}Installing Agent Friday...${reset}"
    Write-Host ""
}

function Write-Info    { param($msg) Write-Host "  `e[36m▸  $msg`e[0m" }
function Write-Success { param($msg) Write-Host "  `e[32m✓  $msg`e[0m" }
function Write-Warn    { param($msg) Write-Host "  `e[33m⚠  $msg`e[0m" }
function Write-Dim     { param($msg) Write-Host "     `e[2m$msg`e[0m" }
function Write-Fail    { param($msg) Write-Host "  `e[31m✗  $msg`e[0m"; exit 1 }

# ── Config ───────────────────────────────────────────────────────
$REPO_URL    = "https://github.com/FutureSpeakAI/friday-desktop.git"
$INSTALL_DIR = Join-Path $env:USERPROFILE ".friday-desktop"
$VENV_DIR    = Join-Path $INSTALL_DIR "venv"
$PYTHON_VENV = Join-Path $VENV_DIR "Scripts\python.exe"
$PIP_VENV    = Join-Path $VENV_DIR "Scripts\pip.exe"
$CLI_BAT     = Join-Path $INSTALL_DIR "friday.bat"

Write-Banner

# ── 1. Python check ──────────────────────────────────────────────
Write-Info "Checking Python..."

$PythonExe = $null
foreach ($cmd in @("python", "python3")) {
    try {
        $ver = & $cmd -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}')" 2>$null
        $parts = $ver -split "\."
        if ([int]$parts[0] -ge 3 -and [int]$parts[1] -ge 10) {
            $PythonExe = $cmd
            Write-Success "Python $ver  ($cmd)"
            break
        }
        else {
            Write-Warn "Found Python $ver — need 3.10 or later"
        }
    }
    catch { }
}

if (-not $PythonExe) {
    Write-Fail "Python 3.10+ not found.

  Download Python from: https://www.python.org/downloads/windows/

  Make sure to check 'Add Python to PATH' during installation.
  Then re-run this installer."
}

# ── 2. Git check ─────────────────────────────────────────────────
try {
    $gitVer = git --version 2>$null
    Write-Success $gitVer
}
catch {
    Write-Fail "git not found.

  Download Git for Windows from: https://git-scm.com/download/win
  Then re-run this installer."
}

# ── 3. Clone or update ───────────────────────────────────────────
Write-Host ""
if (Test-Path (Join-Path $INSTALL_DIR ".git")) {
    Write-Info "Updating existing installation at $INSTALL_DIR..."
    git -C $INSTALL_DIR pull --ff-only origin main
}
else {
    Write-Info "Cloning Agent Friday to $INSTALL_DIR..."
    git clone --depth=1 $REPO_URL $INSTALL_DIR
}
Write-Success "Repository ready"

# ── 4. Virtual environment ───────────────────────────────────────
Write-Host ""
if (-not (Test-Path $VENV_DIR)) {
    Write-Info "Creating Python virtual environment..."
    & $PythonExe -m venv $VENV_DIR
}
Write-Success "Virtual environment ready"

# ── 5. Install dependencies ──────────────────────────────────────
Write-Host ""
Write-Info "Installing dependencies..."
& $PIP_VENV install --quiet --upgrade pip
& $PIP_VENV install --quiet -r (Join-Path $INSTALL_DIR "requirements.txt")

Write-Success "Dependencies installed"

# ── 6. Build UI ──────────────────────────────────────────────────
Write-Host ""
Write-Info "Building UI..."
& $PYTHON_VENV (Join-Path $INSTALL_DIR "build_ui.py") | Out-Null
Write-Success "index.html built"

# ── 7. Create friday.bat ─────────────────────────────────────────
Write-Host ""
Write-Info "Creating friday.bat..."

$batContent = @"
@echo off
:: Agent Friday CLI — auto-generated by install.ps1
set FRIDAY_INSTALL_DIR=$INSTALL_DIR
cd /d "$INSTALL_DIR"
call "$VENV_DIR\Scripts\activate.bat"
python "$INSTALL_DIR\friday_cli.py" %*
"@

$batContent | Out-File -FilePath $CLI_BAT -Encoding ascii
Write-Success "Created $CLI_BAT"

# ── 8. Add to PATH ───────────────────────────────────────────────
$UserPath = [Environment]::GetEnvironmentVariable("PATH", "User")
if ($UserPath -notlike "*$INSTALL_DIR*") {
    [Environment]::SetEnvironmentVariable("PATH", "$UserPath;$INSTALL_DIR", "User")
    $env:PATH = "$env:PATH;$INSTALL_DIR"
    Write-Dim "Added $INSTALL_DIR to user PATH"
}
Write-Success "PATH updated"

# ── Done ─────────────────────────────────────────────────────────
Write-Host ""
Write-Host "  `e[32m`e[1m╔══════════════════════════════════════════╗`e[0m"
Write-Host "  `e[32m`e[1m║  Agent Friday installed successfully!    ║`e[0m"
Write-Host "  `e[32m`e[1m╚══════════════════════════════════════════╝`e[0m"
Write-Host ""
Write-Host "  `e[36m`e[1mNext step:`e[0m  run the setup wizard"
Write-Host ""
Write-Host "      `e[1mfriday setup`e[0m"
Write-Host ""
Write-Warn "Open a new terminal window for the 'friday' command to work in PATH."
Write-Host ""

# ── Offer to run setup now ───────────────────────────────────────
$runNow = Read-Host "  Run setup now? [Y/n]"
if ($runNow -eq "" -or $runNow -match "^[Yy]") {
    Write-Host ""
    & $PYTHON_VENV (Join-Path $INSTALL_DIR "setup_wizard.py")
}
